# Generated by Django 5.2.1 on 2025-05-23 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('placement', models.CharField(choices=[('header', 'Header'), ('mid-content', 'Mid-Content'), ('footer', 'Footer'), ('sidebar', 'Sidebar')], max_length=20)),
                ('ad_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('meta_description', models.CharField(max_length=160)),
                ('template_type', models.CharField(choices=[('how_to', 'How-To Guide'), ('listicle', 'Listicle'), ('news', 'News Article'), ('review', 'Review'), ('opinion', 'Opinion/Editorial')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('avg_time_on_page', models.FloatField(blank=True, null=True)),
                ('seo_score', models.IntegerField(blank=True, null=True)),
                ('keyword_density', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('avg_time_on_page', models.FloatField(blank=True, null=True)),
                ('bounce_rate', models.FloatField(blank=True, null=True)),
                ('conversion_rate', models.FloatField(blank=True, null=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='blog.blogpost')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrendingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('location', models.CharField(choices=[('global', 'Global'), ('us', 'United States'), ('uk', 'United Kingdom'), ('ca', 'Canada'), ('au', 'Australia'), ('in', 'India')], default='global', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('filtered_out', models.BooleanField(default=False)),
                ('filter_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp', 'rank'],
                'unique_together': {('keyword', 'timestamp', 'location')},
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='trending_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blog.trendingtopic'),
        ),
    ]
