# Generated by Django 5.2.1 on 2025-05-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtopic',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trendingtopic',
            name='increase_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trendingtopic',
            name='related_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trendingtopic',
            name='search_volume',
            field=models.IntegerField(default=0),
        ),
    ]
