# Generated by Django 5.2.1 on 2025-06-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_trendingtopic_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtopic',
            name='is_fallback',
            field=models.BooleanField(default=False, help_text='Indicates if this is a manually added fallback topic'),
        ),
    ]
